In [1]:
print("hello world")

hello world


In [2]:
!pip3 install numpy

In [3]:
import numpy as np


In [4]:
arr=np.array([[1,2,3],[4,2,5]]) 

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr.size

6

In [12]:
c=np.zeros((3,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [3]:
import numpy as np

In [11]:
arr=np.array([[1,2,3,4],[3,4,5,7],[7,8,6,5],[2,3,4,5]])

In [12]:
arr.reshape((3,6))

ValueError: cannot reshape array of size 16 into shape (3,6)

In [13]:
arr[1:,:3]

array([[3, 4, 5],
       [7, 8, 6],
       [2, 3, 4]])

In [14]:
arr.T

array([[1, 3, 7, 2],
       [2, 4, 8, 3],
       [3, 5, 6, 4],
       [4, 7, 5, 5]])

In [15]:
arr.max()

8

In [16]:
arr.max(axis=0)

array([7, 8, 6, 7])

In [17]:
np.sort(arr,axis=None)

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 7, 7, 8])

In [18]:
a=np.array([[1,2],[2,1]])
b=np.array([[22,33],[44,55]])
np.vstack((a,b))

array([[ 1,  2],
       [ 2,  1],
       [22, 33],
       [44, 55]])